### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by nawidwwww** [CyniaAI/BuilderGPT#18]
I keep on getting errors when trying to tru the exe and py. when i run the exe i get a dll error. when i run the py this is what comes on the cmd ---(Advanced Mode) Generating programme...
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\nawid\Downloads\BuilderGPT-1.3.0\ui.py", line 89, in generate_schematic
    schem = get_schematic_advanced(description, process_label)
  File "C:\Users\nawid\Downloads\BuilderGPT-1.3.0\ui.py", line 42, in get_schematic_advanced
    programme = core.askgpt(config.BTR_DESC_SYS_GEN, config.BTR_DESC_USR_GEN.replace("%DESCRIPTION%", description), config.GENERATE_MODEL, disable_json_mode=True)
  File "C:\Users\nawid\Downloads\BuilderGPT-1.3.0\core.py", line 77, in askgpt
    logger(f"askgpt: response {response}")
  File "C:\Users\nawid\Downloads\BuilderGPT-1.3.0\log_writer.py", line 26, in logger
    log_file.write(log_line)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 331-345: character maps to <undefined>
also fix the link to your discord

**Comment by Zhou-Shilin** [comment]
I'll fix it tomorrow. Thanks for your feedback~~

**Comment by Zhou-Shilin** [comment]
Could you please try this build:
https://github.com/Zhou-Shilin/BuilderGPT/actions/runs/9382511454/artifacts/1570525159
@nawidwwww

**Comment by Zhou-Shilin** [comment]
I tested it on my side it was fine, so I just MERGE it. If you still have problems, just reopen the issue.
