### ISSUE TITLE
cx_Freeze: Python error in main script

### ISSUE THREAD

**Issue by Cebahh** [CyniaAI/BuilderGPT#36]
Traceback (most recent call last):
File
"C:\hostedtoolcache\windows\Python\3.12.4\x64\Lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 141, in run
File
"C:\hostedtoolcache\windows\Python\3.12.4\x64\Lib\site-packages\cx_Freeze\initscripts\console.py", line 25, in run File "ui.py", line 1, in <module>
File "D:\a\BuilderGPT\BuilderGPT\cube_qgui\__init__.py", line 8, in <module>
File "D:\a\BuilderGPT\Builder GPT\cube_qgui\base_tools.py", line 12, in <module>
File "D:\a\BuilderGPT\BuilderGPT\cube_qgui\manager.py", line 10, in <module>
File "C:\hostedtoolcache\windows\Python\3.12.4\x64\Lib\site-pack ages\ttkbootstrap\__init__.py", line 1, in <module>
File "C:\hostedtoolcache\windows\Python\3.12.4\x64\Lib\site-pack ages\ttkbootstrap\style.py", line 13, in <module> ImportError: cannot import name 'utility' from partially initialized module 'ttkbootstrap' (most likely due to a circular import)
(C:\Users\Thomas\Desktop\build\exe.win-amd64-3.12\lib\ttkbootstrap\_init__.pyc)

Anything i've done wrong?

**Comment by Zhou-Shilin** [comment]
Try bash `pip install ttkbootstrap==0.5.1 --force-reinstall`

**Comment by Jeffrey131313** [comment]
> Try bash `pip install ttkbootstrap==0.5.1 --force-reinstall`

~~So why not add the version requirements to requirements.txt?~~
I used the 2.0.0 source code, so it was not added.

**Comment by Zhou-Shilin** [comment]
We will release that change after a major feature update.
