### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Noel706** [CyniaAI/BuilderGPT#38]
C:\Users\Noel\Desktop\BuilderGPT-main>python ui.py
Traceback (most recent call last):
  File "C:\Users\Noel\Desktop\BuilderGPT-main\ui.py", line 1, in <module>
    from cube_qgui.__init__ import CreateQGUI
  File "C:\Users\Noel\Desktop\BuilderGPT-main\cube_qgui\__init__.py", line 8, in <module>
    import cube_qgui.base_tools
  File "C:\Users\Noel\Desktop\BuilderGPT-main\cube_qgui\base_tools.py", line 12, in <module>
    from cube_qgui.manager import *
  File "C:\Users\Noel\Desktop\BuilderGPT-main\cube_qgui\manager.py", line 10, in <module>
    from ttkbootstrap import Style
ModuleNotFoundError: No module named 'ttkbootstrap'

C:\Users\Noel\Desktop\BuilderGPT-main>

have i done something wrong?

**Comment by Zhou-Shilin** [comment]
`pip install -r requirements.txt`
